# SOPS configuration
# Encrypts secrets with age key

creation_rules:
  # Match secret yaml files in service and provider directories
  - path_regex: (openproject|twenty|discourse|bigbluebutton|kamatera-vps|dns)/.*\.yaml$
    age: age1mkelwyppmll44ehjnarunmtamcxpee7jljyl475mlvxma7dm4f3q6lnmks
